# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'ProjectApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectApp
  pod 'Alamofire', '~> 5.8'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'KeychainSwift', '~> 20.0'

  target 'ProjectAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjectAppUITests' do
    # Pods for testing
  end

end
