# Minimal Podfile for reliable installation
platform :ios, '17.0'

target 'ProjectApp' do
  use_frameworks!

  # Start with minimal, stable dependencies
  pod 'Alamofire', '~> 5.6'
  pod 'SwiftyJSON', '~> 5.0'

end
