name: iOS Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install CocoaPods (if needed)
      run: |
        cd ios
        if [ -f "Podfile" ]; then
          sudo gem install cocoapods
          pod install --repo-update
        else
          echo "No Podfile found, building without CocoaPods"
        fi
        
    - name: Build iOS app for Simulator
      run: |
        cd ios
        if [ -f "ProjectApp.xcworkspace" ]; then
          echo "Building with workspace (CocoaPods)"
          xcodebuild -workspace ProjectApp.xcworkspace -scheme ProjectApp -destination 'platform=iOS Simulator,name=iPhone 15' build
        else
          echo "Building with project file (no CocoaPods)"
          xcodebuild -project ProjectApp.xcodeproj -scheme ProjectApp -destination 'platform=iOS Simulator,name=iPhone 15' build
        fi
        
    - name: Archive iOS app
      run: |
        cd ios
        if [ -f "ProjectApp.xcworkspace" ]; then
          echo "Archiving with workspace (CocoaPods)"
          xcodebuild -workspace ProjectApp.xcworkspace -scheme ProjectApp -destination generic/platform=iOS archive -archivePath ProjectApp.xcarchive
        else
          echo "Archiving with project file (no CocoaPods)"
          xcodebuild -project ProjectApp.xcodeproj -scheme ProjectApp -destination generic/platform=iOS archive -archivePath ProjectApp.xcarchive
        fi
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-${{ github.run_number }}
        path: ios/ProjectApp.xcarchive
        retention-days: 30
